In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
loan = pd.read_csv("loanf.csv")

In [3]:
loan.keys()

Index(['Interest.Rate', 'FICO.Score', 'Loan.Length', 'Monthly.Income',
       'Loan.Amount'],
      dtype='object')

In [4]:
##lets take Interest Rate as the dependent variable and FICO score and Loan Amount as Independent

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
loan["NewInterest"] = loan["Interest.Rate"] < 17

In [13]:
loan

Interest.Rate  FICO.Score  Loan.Length  Monthly.Income  Loan.Amount  \
6             15.31         670           36         4891.67         6000   
11            19.72         670           36         3575.00         2000   
12            14.27         665           36         4250.00        10625   
13            21.67         670           60        14166.67        28000   
21            21.98         665           36         6666.67        22000   
...             ...         ...          ...             ...          ...   
2472           7.90         770           36         5166.67        19000   
2481           6.03         760           36         5000.00        10000   
2482           6.62         810           36         9250.00        27000   
2486          10.75         765           36         7083.33        25000   
2497          14.09         740           60         8903.25        16000   

      NewInterest  
6            True  
11          False  
12           True  
13          False  
21          False  
...           ...  
2472         True  
2481         True  
2482         True  
2486         True  
2497         True  

[2500 rows x 6 columns]

In [14]:
x = loan[["FICO.Score","Loan.Amount"]].values
y = loan["NewInterest"].values

In [15]:
regressor = LogisticRegression()
regressor = regressor.fit(x,y)

In [16]:
pred = regressor.predict(x)

In [17]:
sig = 1/(1+np.exp(-1*pred))

In [18]:
sig

array([0.73105858, 0.73105858, 0.73105858, ..., 0.73105858, 0.73105858,
       0.73105858])

In [20]:
regressor.predict([[14, 200]])

array([ True])

In [21]:
regressor.predict_proba([[14, 200]])

array([[0.49026574, 0.50973426]])

In [22]:
def Loan_Approve(FICO,amt):
    out = regressor.predict_proba([[FICO,amt]])
    if out[0][0] > 0.5:
        print("Loan not approved")
    else:
        print("Loan Approved")

In [23]:
Loan_Approve(14,200)

Loan Approved


In [24]:
from ipywidgets import interact

In [25]:
interact(Loan_Approve, FICO = (50, 1200), amt = (200, 100000))

interactive(children=(IntSlider(value=625, description='FICO', max=1200, min=50), IntSlider(value=50100, descr…

<function __main__.Loan_Approve(FICO, amt)>

In [26]:
#Save your trained model

In [28]:
import joblib

In [30]:
joblib.dump(regressor, "loan_approve_or_not.pkl")

['loan_approve_or_not.pkl']